plugins {
	id 'java'
	id 'org.springframework.boot' version '3.3.2'
	id 'io.spring.dependency-management' version '1.1.6'
	id "org.asciidoctor.jvm.convert" version "3.3.2"
	id 'com.epages.restdocs-api-spec' version '0.18.2'
}

group = 'com.sunyesle'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
	asciidoctorExt
}

repositories {
	mavenCentral()
}

ext {
	snippetsDir = file('build/generated-snippets')
}

test {
	outputs.dir snippetsDir
	useJUnitPlatform {
		excludeTags('restdocs')
	}
}

tasks.register('restDocsTest', Test) {
	outputs.dir snippetsDir
	useJUnitPlatform {
		includeTags('restdocs')
	}
}

asciidoctor {
	dependsOn restDocsTest

	inputs.dir snippetsDir
	configurations 'asciidoctorExt'
	sources {
		include("**/index.adoc")
	}
	baseDirFollowsSourceFile()
}

tasks.register('copyDocument', Copy) {
	dependsOn asciidoctor

	from file("${asciidoctor.outputDir}")
	into file("src/main/resources/static/docs")

	doFirst {
		delete file("src/main/resources/static/docs")
	}
}

openapi3 {
	servers = [
			{
				url = "http://localhost:8080"
				description = "local server"
			}
	]
	title = "Test service API docs"
	description = "OpenApi Specification 3.0 기반의 API 문서입니다"
	version = "0.0.1"
	format = "yaml"
}

tasks.register('copyOasToSwagger', Copy) {
	dependsOn "openapi3"

	from "${buildDir}/api-spec/openapi3.yaml"
	into "src/main/resources/static/swagger/"

	doFirst {
		delete "src/main/resources/static/swagger/openapi3.yaml"

		// 빌드 디렉토리 yaml 파일에 보안 스키마 추가
		def openapi3File = file("$buildDir/api-spec/openapi3.yaml")

		// JWT 인증을 위한 securitySchemes와 security 요소를 정의한다.
		def securitySchemesContent =
				"  securitySchemes:\n" +
				"    BearerAuth:\n" +
				"      type: http\n" +
				"      scheme: bearer\n" +
				"      bearerFormat: JWT\n" +
				"security:\n" +
				"  - BearerAuth: []  # Apply the security scheme here"

		// openapi3.yaml 파일에 내용을 추가한다.
		if (openapi3File.exists()) {
			openapi3File.append(securitySchemesContent)
		} else {
			println "Warning: openapi3.yaml not found at ${openapi3File.path}"
		}
	}
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-validation'

	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	testCompileOnly 'org.projectlombok:lombok'
	testAnnotationProcessor 'org.projectlombok:lombok'

	runtimeOnly 'com.h2database:h2'

	developmentOnly 'org.springframework.boot:spring-boot-devtools'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.security:spring-security-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	// sql 로깅
	implementation 'com.github.gavlyukovskiy:p6spy-spring-boot-starter:1.9.1'

	// 인수 테스트
	testImplementation 'io.rest-assured:rest-assured:5.5.0'

	// Swagger
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.5.0'

	// REST Docs
	testImplementation 'org.springframework.restdocs:spring-restdocs-mockmvc'
	asciidoctorExt 'org.springframework.restdocs:spring-restdocs-asciidoctor'
	testImplementation 'com.epages:restdocs-api-spec-mockmvc:0.18.2'

	// JWT
	implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
	runtimeOnly 'io.jsonwebtoken:jjwt-orgjson:0.12.6'
}
